In [2]:
import numpy as np

In [9]:
np.random.seed(123)

In [ ]:
def model(x:np.array):
    w = np.array([2, 3, 7, -1])
    b = 3
    return np.dot(x, w) + b

In [ ]:
def generate_random_samples(model:callable, N:int=50):
    x = np.sort(10 * np.random.rand(N))
    yerr = 0.1 + 0.5 * np.random.rand(N)
    y = 
    y += np.abs(f_true * y) * np.random.randn(N)
    y += yerr * np.random.randn(N)

In [7]:
# Una muestra de 50 vectores de 4 elementos aleatorios
samples = np.random.rand(5, 4)
samples

array([[0.96644508, 0.75740105, 0.81557786, 0.23486752],
       [0.06015517, 0.45048989, 0.30313971, 0.67433   ],
       [0.92589822, 0.18464468, 0.09691422, 0.09746362],
       [0.85060665, 0.4205465 , 0.29525828, 0.4564924 ],
       [0.79026898, 0.2440644 , 0.17621123, 0.72919818]])

In [8]:
10*samples

array([[9.66445078, 7.57401054, 8.15577862, 2.3486752 ],
       [0.60155173, 4.50489891, 3.03139707, 6.74330004],
       [9.25898225, 1.84644683, 0.96914223, 0.97463616],
       [8.50606651, 4.20546504, 2.95258279, 4.56492405],
       [7.90268979, 2.44064401, 1.76211227, 7.29198175]])

In [9]:
w = np.array([2, 3, 7, -1])
np.dot(10*samples,w)

array([96.79270831, 29.19427967, 29.86666444, 45.73168367, 28.17011572])

In [11]:
np.dot(10*samples[0],w)

np.float64(96.79270831377018)

In [15]:
np.dot( np.sort(10*np.random.rand(50, 4)), np.array([2, 3, 7, -1]) ) + 3

array([41.55744636, 42.51469795, 48.96291229, 56.9352762 , 41.15568685,
       66.10382621, 37.42607506, 39.25676793, 25.97339416, 48.1549169 ,
       45.58102603, 81.59603002,  8.68582288, 58.47719499, 20.61511518,
       71.9389302 , 42.55806816,  5.94008528, 65.48761197, 81.03543499,
       15.68621745, 42.40332752, 50.75839983,  9.72766648, 41.77381883,
       41.86135511, 15.0913301 , 82.64167209, 35.05090918, 49.27531722,
       48.66318706, 59.20972307, 41.28636204, 59.0533083 , 96.16686858,
       80.66587629, 70.85613578, 43.32553532, 56.52505171, 67.45442182,
       79.08926545, 17.52376265, 24.21049148, 35.31722197, 54.71177777,
       10.05250378, 24.70004317, 73.12851087, 48.28610929, 69.0757211 ])